name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: yarn install
      - run: yarn lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: yarn install
      - run: yarn node-test-with-coverage

  floating-deps:
    name: Tests (floating dependencies)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: yarn install --no-lockfile
      - run: yarn node-test

  all-commands-smoke-tests:
    name: Tests (commands smoke test)
    runs-on: ubuntu-latest

    needs:
      - lint
      - tests
      - floating-deps

    strategy:
      fail-fast: false
      matrix:
        command:
          # try:each
          - ./node_modules/.bin/ember try:each

          # skip-cleanup option
          - ./node_modules/.bin/ember try:each --skip-cleanup

          # config-path option
          - ./node_modules/.bin/ember try:each --config-path='../test/fixtures/dummy-ember-try-config.js'

          # both ember-try options
          - ./node_modules/.bin/ember try:each --config-path='../test/fixtures/dummy-ember-try-config.js' --skip-cleanup true

          # try:ember
          - ./node_modules/.bin/ember try:ember '> 3.16.0 < 3.28.0'
          - ./node_modules/.bin/ember try:ember '3.18.0' --config-path='../test/fixtures/dummy-ember-try-config.js'
          - ./node_modules/.bin/ember try:ember '3.24.0' --skip-cleanup=true

          # try:config
          - ./node_modules/.bin/ember try:config
          - ./node_modules/.bin/ember try:config --config-path='../test/fixtures/dummy-ember-try-config.js'

          # try:one <scenario>
          - ./node_modules/.bin/ember try:one default

          # custom command
          - ./node_modules/.bin/ember try:one default --- ember help

          # skip-cleanup option
          - ./node_modules/.bin/ember try:one default --skip-cleanup

          # config-path option
          - ./node_modules/.bin/ember try:one test1 --config-path='../test/fixtures/dummy-ember-try-config.js'

          # both ember-try options
          - ./node_modules/.bin/ember try:one test1 --config-path='../test/fixtures/dummy-ember-try-config.js' --skip-cleanup true

          # custom command with options to command
          - ./node_modules/.bin/ember try:one default --- ember help --silent

          # custom command mixed with ember try's own option
          - ./node_modules/.bin/ember try:one default --skip-cleanup --- ember help --silent

          # try:reset
          - ./node_modules/.bin/ember try:reset

          # Environment variables availability
          - FOO="5" ./node_modules/.bin/ember try:one default --- ./fail-if-no-foo.sh

          - ./node_modules/.bin/ember try:one default --- FOO=5 ./fail-if-no-foo.sh

          # Custom, compound commands
          - ./node_modules/.bin/ember try:one default --- 'echo 1 && echo 2'

          # Environment variables from config
          - ./node_modules/.bin/ember try:each --config-path='../test/fixtures/dummy-ember-try-config-different-env-vars.js'


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: install deps
        run: yarn install
      - name: install smoke-test-app deps
        # using `npm` to install in the smoke-test-app so that `file:` will be treated
        # as a symlink (npm handles `file:../` as symlink, and `yarn` treats it
        # as "copy into this directory")
        run: npm install
        working-directory: smoke-test-app
      - run: ${{ matrix.command }}
        working-directory: smoke-test-app

  npm-smoke-tests:
    strategy:
      matrix:
        node: ['14', '16', '18']

    name: Smoke Tests (Node v${{ matrix.node }} with npm)
    runs-on: ubuntu-latest

    needs:
      - lint
      - tests

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install deps
        run: yarn install
      - name: install smoke-test-app deps
        run: npm install
        working-directory: smoke-test-app
      - run:  ./node_modules/.bin/ember try:one test2 --config-path='../test/fixtures/dummy-ember-try-config-with-npm-scenarios.js'
        working-directory: smoke-test-app

  yarn-smoke-tests:
    strategy:
      matrix:
        node: ['14', '16', '18']

    name: Smoke Tests (Node v${{ matrix.node }} with yarn)
    runs-on: ubuntu-latest

    needs:
      - lint
      - tests

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install deps
        run: yarn install
      - name: install smoke-test-app deps
        run: yarn install
        working-directory: smoke-test-app
      - run:  ./node_modules/.bin/ember try:one test2 --config-path='../test/fixtures/dummy-ember-try-config-with-yarn-scenarios.js'
        working-directory: smoke-test-app

  windows-smoke-tests:
    name: Smoke Tests (Windows)
    runs-on: windows-latest

    needs:
      - lint
      - tests

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: install deps
        run: yarn install
      - name: install smoke-test-app deps
        run: npm install
        working-directory: smoke-test-app
      - run:  ./node_modules/.bin/ember try:one test2 --config-path='../test/fixtures/dummy-ember-try-config-with-npm-scenarios.js'
        working-directory: smoke-test-app
